services:
  # Servizio API
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: db
    ports:
      - '80:8000'
    restart: "no"
    depends_on:
      - db  # Assicurati che il servizio API dipenda dal database MySQL

  # Servizio MySQL
  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Password dell'utente root
      MYSQL_DATABASE: db       # Nome del database da creare
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: no

  # Servizio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"  # phpMyAdmin sarà accessibile su http://localhost:8080
    depends_on:
      - db
    restart: no

# Volumes per i dati persistenti
volumes:
  db_data:
